# Generated by Django 5.1.7 on 2025-04-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=155)),
                ('descricao', models.TextField(blank=True)),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
